// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wal-g/wal-g/internal/databases/postgres (interfaces: Cleaner)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/cleaner.go -package=mocks . Cleaner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCleaner is a mock of Cleaner interface.
type MockCleaner struct {
	ctrl     *gomock.Controller
	recorder *MockCleanerMockRecorder
	isgomock struct{}
}

// MockCleanerMockRecorder is the mock recorder for MockCleaner.
type MockCleanerMockRecorder struct {
	mock *MockCleaner
}

// NewMockCleaner creates a new mock instance.
func NewMockCleaner(ctrl *gomock.Controller) *MockCleaner {
	mock := &MockCleaner{ctrl: ctrl}
	mock.recorder = &MockCleanerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCleaner) EXPECT() *MockCleanerMockRecorder {
	return m.recorder
}

// GetFiles mocks base method.
func (m *MockCleaner) GetFiles(directory string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFiles", directory)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFiles indicates an expected call of GetFiles.
func (mr *MockCleanerMockRecorder) GetFiles(directory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFiles", reflect.TypeOf((*MockCleaner)(nil).GetFiles), directory)
}

// Remove mocks base method.
func (m *MockCleaner) Remove(file string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", file)
}

// Remove indicates an expected call of Remove.
func (mr *MockCleanerMockRecorder) Remove(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockCleaner)(nil).Remove), file)
}
