FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm-256color

COPY docker/ubuntu/config/apt/ /var/lib/dist/config/apt
RUN cp --force --recursive --verbose /var/lib/dist/config/apt/* /etc/apt/

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        wget \
        curl \
        git \
        ca-certificates \
        htop \
        nano \
        less && \
    rm -rf /var/lib/apt/lists/*
