// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Enveloper is an autogenerated mock type for the Enveloper type
type Enveloper struct {
	mock.Mock
}

type Enveloper_Expecter struct {
	mock *mock.Mock
}

func (_m *Enveloper) EXPECT() *Enveloper_Expecter {
	return &Enveloper_Expecter{mock: &_m.Mock}
}

// DecryptKey provides a mock function with given fields: _a0
func (_m *Enveloper) DecryptKey(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Enveloper_DecryptKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptKey'
type Enveloper_DecryptKey_Call struct {
	*mock.Call
}

// DecryptKey is a helper method to define mock.On call
//   - _a0 []byte
func (_e *Enveloper_Expecter) DecryptKey(_a0 interface{}) *Enveloper_DecryptKey_Call {
	return &Enveloper_DecryptKey_Call{Call: _e.mock.On("DecryptKey", _a0)}
}

func (_c *Enveloper_DecryptKey_Call) Run(run func(_a0 []byte)) *Enveloper_DecryptKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Enveloper_DecryptKey_Call) Return(_a0 []byte, _a1 error) *Enveloper_DecryptKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Enveloper_DecryptKey_Call) RunAndReturn(run func([]byte) ([]byte, error)) *Enveloper_DecryptKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetEncryptedKey provides a mock function with given fields: r
func (_m *Enveloper) GetEncryptedKey(r io.Reader) ([]byte, error) {
	ret := _m.Called(r)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader) ([]byte, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) []byte); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Enveloper_GetEncryptedKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEncryptedKey'
type Enveloper_GetEncryptedKey_Call struct {
	*mock.Call
}

// GetEncryptedKey is a helper method to define mock.On call
//   - r io.Reader
func (_e *Enveloper_Expecter) GetEncryptedKey(r interface{}) *Enveloper_GetEncryptedKey_Call {
	return &Enveloper_GetEncryptedKey_Call{Call: _e.mock.On("GetEncryptedKey", r)}
}

func (_c *Enveloper_GetEncryptedKey_Call) Run(run func(r io.Reader)) *Enveloper_GetEncryptedKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *Enveloper_GetEncryptedKey_Call) Return(_a0 []byte, _a1 error) *Enveloper_GetEncryptedKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Enveloper_GetEncryptedKey_Call) RunAndReturn(run func(io.Reader) ([]byte, error)) *Enveloper_GetEncryptedKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with given fields:
func (_m *Enveloper) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Enveloper_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Enveloper_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Enveloper_Expecter) GetName() *Enveloper_GetName_Call {
	return &Enveloper_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Enveloper_GetName_Call) Run(run func()) *Enveloper_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Enveloper_GetName_Call) Return(_a0 string) *Enveloper_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Enveloper_GetName_Call) RunAndReturn(run func() string) *Enveloper_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// SerializeEncryptedKey provides a mock function with given fields: encryptedKey
func (_m *Enveloper) SerializeEncryptedKey(encryptedKey []byte) []byte {
	ret := _m.Called(encryptedKey)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(encryptedKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// Enveloper_SerializeEncryptedKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SerializeEncryptedKey'
type Enveloper_SerializeEncryptedKey_Call struct {
	*mock.Call
}

// SerializeEncryptedKey is a helper method to define mock.On call
//   - encryptedKey []byte
func (_e *Enveloper_Expecter) SerializeEncryptedKey(encryptedKey interface{}) *Enveloper_SerializeEncryptedKey_Call {
	return &Enveloper_SerializeEncryptedKey_Call{Call: _e.mock.On("SerializeEncryptedKey", encryptedKey)}
}

func (_c *Enveloper_SerializeEncryptedKey_Call) Run(run func(encryptedKey []byte)) *Enveloper_SerializeEncryptedKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Enveloper_SerializeEncryptedKey_Call) Return(_a0 []byte) *Enveloper_SerializeEncryptedKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Enveloper_SerializeEncryptedKey_Call) RunAndReturn(run func([]byte) []byte) *Enveloper_SerializeEncryptedKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewEnveloper creates a new instance of Enveloper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnveloper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Enveloper {
	mock := &Enveloper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
