// Code generated by Yandex patched mockery v1.1.0. DO NOT EDIT.

package archivemocks

import (
	internal "github.com/wal-g/wal-g/internal"
	archive "github.com/wal-g/wal-g/internal/databases/mongo/archive"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// BackupListing is an autogenerated mock type for the BackupListing type
type BackupListing struct {
	mock.Mock
}

// Backups provides a mock function with given fields: backups, output
func (_m *BackupListing) Backups(backups []archive.Backup, output io.Writer) error {
	ret := _m.Called(backups, output)

	var r0 error
	if rf, ok := ret.Get(0).(func([]archive.Backup, io.Writer) error); ok {
		r0 = rf(backups, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Names provides a mock function with given fields: backups, output
func (_m *BackupListing) Names(backups []internal.BackupTime, output io.Writer) error {
	ret := _m.Called(backups, output)

	var r0 error
	if rf, ok := ret.Get(0).(func([]internal.BackupTime, io.Writer) error); ok {
		r0 = rf(backups, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
