// Code generated by mockery v2.53.5. DO NOT EDIT.

package archivemocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
	internal "github.com/wal-g/wal-g/internal"
	models "github.com/wal-g/wal-g/internal/databases/mongo/models"
)

// Downloader is an autogenerated mock type for the Downloader type
type Downloader struct {
	mock.Mock
}

// BackupMeta provides a mock function with given fields: ctx, name
func (_m *Downloader) BackupMeta(ctx context.Context, name string) (*models.Backup, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for BackupMeta")
	}

	var r0 *models.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Backup, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Backup); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DownloadOplogArchive provides a mock function with given fields: ctx, arch, writeCloser
func (_m *Downloader) DownloadOplogArchive(ctx context.Context, arch models.Archive, writeCloser io.WriteCloser) error {
	ret := _m.Called(ctx, arch, writeCloser)

	if len(ret) == 0 {
		panic("no return value specified for DownloadOplogArchive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Archive, io.WriteCloser) error); ok {
		r0 = rf(ctx, arch, writeCloser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LastKnownArchiveTS provides a mock function with given fields: ctx
func (_m *Downloader) LastKnownArchiveTS(ctx context.Context) (models.Timestamp, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LastKnownArchiveTS")
	}

	var r0 models.Timestamp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (models.Timestamp, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.Timestamp); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.Timestamp)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBackups provides a mock function with given fields: ctx
func (_m *Downloader) ListBackups(ctx context.Context) ([]internal.BackupTime, []string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBackups")
	}

	var r0 []internal.BackupTime
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]internal.BackupTime, []string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []internal.BackupTime); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.BackupTime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []string); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListOplogArchives provides a mock function with given fields: ctx
func (_m *Downloader) ListOplogArchives(ctx context.Context) ([]models.Archive, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListOplogArchives")
	}

	var r0 []models.Archive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Archive, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Archive); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Archive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOplogArchivesSegment provides a mock function with given fields: ctx, startAfter, endBefore
func (_m *Downloader) ListOplogArchivesSegment(ctx context.Context, startAfter *string, endBefore *string) ([]models.Archive, error) {
	ret := _m.Called(ctx, startAfter, endBefore)

	if len(ret) == 0 {
		panic("no return value specified for ListOplogArchivesSegment")
	}

	var r0 []models.Archive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, *string) ([]models.Archive, error)); ok {
		return rf(ctx, startAfter, endBefore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, *string) []models.Archive); ok {
		r0 = rf(ctx, startAfter, endBefore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Archive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, *string) error); ok {
		r1 = rf(ctx, startAfter, endBefore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadBackups provides a mock function with given fields: ctx, names
func (_m *Downloader) LoadBackups(ctx context.Context, names []string) ([]*models.Backup, error) {
	ret := _m.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for LoadBackups")
	}

	var r0 []*models.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*models.Backup, error)); ok {
		return rf(ctx, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*models.Backup); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, names)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDownloader creates a new instance of Downloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Downloader {
	mock := &Downloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
