// Code generated by Yandex patched mockery v1.1.0. DO NOT EDIT.

package archivemocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/wal-g/wal-g/internal/databases/mongo/models"
)

// MongoMetaConstructor is an autogenerated mock type for the MongoMetaConstructor type
type MongoMetaConstructor struct {
	mock.Mock
}

// Finalize provides a mock function with given fields: backupName
func (_m *MongoMetaConstructor) Finalize(backupName string) error {
	ret := _m.Called(backupName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(backupName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Init provides a mock function with given fields: permanent
func (_m *MongoMetaConstructor) Init(permanent bool) error {
	ret := _m.Called(permanent)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(permanent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Meta provides a mock function with given fields:
func (_m *MongoMetaConstructor) Meta() models.BackupMeta {
	ret := _m.Called()

	var r0 models.BackupMeta
	if rf, ok := ret.Get(0).(func() models.BackupMeta); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.BackupMeta)
	}

	return r0
}
