Document: wal-g
Title: Debian wal-g Manual
Author: <insert document author here>
Abstract: This manual describes what wal-g is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wal-g/wal-g.sgml.gz

Format: postscript
Files: /usr/share/doc/wal-g/wal-g.ps.gz

Format: text
Files: /usr/share/doc/wal-g/wal-g.text.gz

Format: HTML
Index: /usr/share/doc/wal-g/html/index.html
Files: /usr/share/doc/wal-g/html/*.html
