FROM bitnami/etcd:latest
# FROM wal-g/ubuntu:latest


# RUN apt-get update && \
#     apt-get install --yes --no-install-recommends --no-install-suggests \
#     etcd

COPY docker/etcd/export_common.sh /usr/local/export_common.sh