FROM wal-g/docker_prefix:latest
RUN apt-get install --yes --no-install-recommends --no-install-suggests jq
RUN chmod -R 777 /tmp/tests

CMD su postgres -c "/tmp/tests/wale_tablespace_compatibility_test.sh"
