FROM wal-g/golang:latest as build

WORKDIR /go/src/github.com/wal-g/wal-g

RUN apt-get update && \
    apt-get install --yes --no-install-recommends --no-install-suggests \
    liblzo2-dev

COPY vendor/ vendor/
COPY internal/ internal/
COPY cmd/ cmd/
COPY main/ main/
COPY utility/ utility/

RUN sed -i 's|#cgo LDFLAGS: -lbrotli.*|&-static -lbrotlicommon-static -lm|' \
        vendor/github.com/google/brotli/go/cbrotli/cgo.go && \
    sed -i 's|\(#cgo LDFLAGS:\) .*|\1 -Wl,-Bstatic -llzo2 -Wl,-Bdynamic|' \
        vendor/github.com/cyberdelia/lzo/lzo.go && \
    cd main/pg && \
    go build -race -o wal-g -tags "brotli lzo" -ldflags "-s -w -X main.BuildDate=`date -u +%Y.%m.%d_%H:%M:%S`"

FROM wal-g/pg:latest

COPY --from=build /go/src/github.com/wal-g/wal-g/main/pg/wal-g /usr/bin

COPY docker/pg_tests/scripts/ /tmp

RUN mkdir -p /tmp/logs/wal_push_logs
RUN mkdir /tmp/logs/wal_fetch_logs
RUN mkdir /tmp/logs/backup_push_logs
RUN mkdir /tmp/logs/backup_fetch_logs
RUN chmod 777 -R tmp/logs/

RUN chmod 777 tmp/configs/