ARG PG_IMAGE=wal-g/pg10:latest

FROM wal-g/golang:latest AS build

WORKDIR /go/src/github.com/wal-g/wal-g

RUN apt-get update && \
    apt-get install --yes --no-install-recommends --no-install-suggests \
    liblzo2-dev \
    curl git

COPY .git .git
COPY .gitmodules .gitmodules
COPY go.mod go.mod
COPY go.sum go.sum
COPY vendor/ vendor/
COPY internal/ internal/
COPY pkg/ pkg/
COPY cmd/ cmd/
COPY main/ main/
COPY utility/ utility/
COPY test/ test/
COPY testtools/ testtools/
COPY link_brotli.sh link_brotli.sh
COPY .github/versions/libsodium-version .github/versions/libsodium-version
COPY link_libsodium.sh link_libsodium.sh
COPY CMakeLists-brotli.txt CMakeLists-brotli.txt
COPY Makefile Makefile

RUN --mount=type=cache,target=/gocache GOCACHE=/gocache \
    go get -v -t ./... && USE_LIBSODIUM=1 USE_BROTLI=1 make ENABLE_RACE_DETECTION=1 deps pg_build build_client

RUN --mount=type=cache,target=/gocache cd pkg/storages/swift && GOCACHE=/gocache go test -v -c
RUN --mount=type=cache,target=/gocache cd pkg/storages/sh && GOCACHE=/gocache go test -v -c

FROM ${PG_IMAGE}

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends --no-install-suggests \
    netcat-openbsd \
    net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/debconf/*

COPY --from=build /go/src/github.com/wal-g/wal-g/pkg/storages/swift/swift.test /tmp/test_bins/
COPY --from=build /go/src/github.com/wal-g/wal-g/pkg/storages/sh/sh.test /tmp/test_bins/
COPY --from=build /go/src/github.com/wal-g/wal-g/main/pg/wal-g /usr/bin
COPY --from=build /go/src/github.com/wal-g/wal-g/bin/walg-daemon-client /usr/bin

COPY docker/pg_tests/scripts/ /tmp

RUN mkdir -p /tmp/logs/ && chmod 777 /tmp/configs/ && chmod 777 /tmp/logs/

RUN chmod 777 /tmp/tests/wal_perftest_with_throttling.sh
