ARG PG_IMAGE=wal-g/pg10:latest

FROM wal-g/golang:latest AS build
ENV GOEXPERIMENT=jsonv2
ENV USE_LIBSODIUM=1

WORKDIR /go/src/github.com/wal-g/wal-g

RUN apt-get update && \
    apt-get install --yes --no-install-recommends --no-install-suggests \
    liblzo2-dev \
    curl

COPY go.mod go.mod
COPY vendor/ vendor/
COPY internal/ internal/
COPY pkg/ pkg/
COPY cmd/ cmd/
COPY main/ main/
COPY utility/ utility/
COPY link_libsodium.sh link_libsodium.sh

RUN ./link_libsodium.sh

RUN sed -i 's|\(#cgo LDFLAGS:\) .*|\1 -Wl,-Bstatic -llzo2 -Wl,-Bdynamic|' \
        vendor/github.com/cyberdelia/lzo/lzo.go
RUN --mount=type=cache,target=/gocache cd main/pg && GOCACHE=/gocache \
    go build -mod vendor -race -o wal-g -tags "brotli lzo libsodium" -ldflags "-s -w -X main.buildDate=`date -u +%Y.%m.%d_%H:%M:%S`"
RUN --mount=type=cache,target=/gocache cd cmd/daemonclient && GOCACHE=/gocache \
    go build -mod vendor -o walg-daemon-client -ldflags "-s -w -X main.buildDate=`date -u +%Y.%m.%d_%H:%M:%S`"

RUN --mount=type=cache,target=/gocache cd pkg/storages/swift && GOCACHE=/gocache go test -v -c
RUN --mount=type=cache,target=/gocache cd pkg/storages/sh && GOCACHE=/gocache go test -v -c

FROM ${PG_IMAGE}

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends --no-install-suggests \
    netcat-openbsd \
    net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/debconf/*

COPY --from=build /go/src/github.com/wal-g/wal-g/pkg/storages/swift/swift.test /tmp/test_bins/
COPY --from=build /go/src/github.com/wal-g/wal-g/pkg/storages/sh/sh.test /tmp/test_bins/
COPY --from=build /go/src/github.com/wal-g/wal-g/main/pg/wal-g /usr/bin
COPY --from=build /go/src/github.com/wal-g/wal-g/cmd/daemonclient/walg-daemon-client /usr/bin

COPY docker/pg_tests/scripts/ /tmp

RUN mkdir -p /tmp/logs/ && chmod 777 /tmp/configs/ && chmod 777 /tmp/logs/

RUN chmod 777 /tmp/tests/wal_perftest_with_throttling.sh
