FROM walg-func-test-base as build

ARG WALG_REPO=${GOPATH}/src/github.com/wal-g/wal-g

# Build WAL-G
COPY staging/wal-g ${WALG_REPO}/
WORKDIR ${WALG_REPO}

# we test wal-g logic, not our deps. So, no brotli in these tests.
RUN cd main/mysql && \
    go build -mod vendor -race -o wal-g -ldflags "-s -w" && \
    cp wal-g /usr/bin/wal-g


FROM ubuntu:focal

ARG MYSQL_MAJOR="8.0"

COPY --from=build /usr/bin/wal-g /usr/bin/wal-g

ENV DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC
ENV MYSQLDATA /var/lib/mysql

# Install MySQL & Co
COPY images/mysql/install_mysql.sh /root/install_mysql.sh
RUN chmod 755 /root/install_mysql.sh
RUN /root/install_mysql.sh

COPY images/mysql/conf/client.cnf /root/.my.cnf
COPY images/mysql/conf/client.cnf /etc/mysql/debian.cnf
COPY images/mysql/conf/init.sql /etc/mysql/init.sql

RUN curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | bash && \
    apt -y install sysbench


# copy testdata:
COPY testdata/ /testdata/
COPY images/mysql/scripts/export_common.sh /usr/local/export_common.sh
COPY images/mysql/scripts/export_test_funcs.sh /usr/local/export_test_funcs.sh

RUN apt-get install --yes --no-install-recommends --no-install-suggests \
  supervisor

COPY images/base/config/supervisor /etc/supervisor
COPY images/mongodb/config /config

CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]