# vim:set ft=dockerfile:
FROM walg-func-test-base

ARG WALG_REPO=${GOPATH}/src/github.com/wal-g/wal-g
ARG REDIS_VERSION=7.2.5

ENV TMP_DIR /var/tmp/wal-g
ENV WALG_CONF_DIR /etc/wal-g/

ENV USER redis
ENV GROUP redis
ENV USERGROUP $USER:$GROUP
ENV HOME /home/$USER
ENV USE_BROTLI 1

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN groupadd -r -g 999 $USER && useradd -r -g $GROUP -u 999 $USER

RUN apt-get update; \
	apt-get upgrade; \
	apt install -y software-properties-common apt-transport-https curl ca-certificates; \
	curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg; \
	echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list
RUN apt-get update; \
	version="6:$REDIS_VERSION-1rl1~$(lsb_release -cs)1"; \
	apt install -y redis-tools=$version redis-server=$version; \
	redis-cli --version; \
	redis-server --version

RUN mkdir -p /data && chown $USERGROUP /data
VOLUME /data
WORKDIR /data

RUN apt-get update -qq && \
    apt-get install -y apt-transport-https && \
    mkdir -p /etc/apt/sources.list.d && \
    apt-get update -qq && \
    apt-key update && \
    rm -rf /var/lib/apt/lists/* /var/cache/debconf && \
    apt-get clean

RUN mkdir -p /var/log/wal-g/ ${TMP_DIR} && \
    ln --force -s /config/supervisor/conf.d/redis.conf /etc/supervisor/conf.d/redis.conf && \
    mkdir -p ${WALG_REPO} ${WALG_CONF_DIR} && \
    mkdir -p $HOME/.gnupg && touch $HOME/.gnupg/gpg.conf && \
    chmod -R 700 $HOME/.gnupg && chown $USERGROUP -R $HOME/.gnupg && \
    ln --force -s /config/wal-g-${REDIS_VERSION}.json ${WALG_CONF_DIR}/wal-g.json && \
    ln --force -s /config/gpg-key.armor ${WALG_CONF_DIR}/gpg-key.armor

COPY staging/wal-g ${WALG_REPO}/
COPY staging/wal-g/redis_cli.sh /usr/bin/redis_cli.sh

WORKDIR ${WALG_REPO}

RUN make link_external_deps
RUN make BUILD_ARGS=-race redis_build && \
    cp main/redis/wal-g /usr/bin/wal-g
