# vim:set ft=dockerfile:
ARG MONGO_PACKAGE=mongodb-org
ARG MONGO_VERSION=

FROM walg-func-test-base AS build

ARG WALG_REPO=${GOPATH}/src/github.com/wal-g/wal-g
ENV USE_BROTLI=1

RUN mkdir -p ${WALG_REPO}
COPY staging/wal-g ${WALG_REPO}/

WORKDIR ${WALG_REPO}

RUN make ENABLE_RACE_DETECTION=1 link_external_deps mongo_build

###

FROM wal-g/mongo-base:${MONGO_PACKAGE}-${MONGO_VERSION}

COPY --from=build /go/src/github.com/wal-g/wal-g/main/mongo/wal-g /usr/bin/wal-g
