// Code generated by MockGen. DO NOT EDIT.
// Source: collector.go
//
// Generated by this command:
//
//	mockgen -source collector.go -destination collector_mock.go -package stats
//

// Package stats is a generated GoMock package.
package stats

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCollector is a mock of Collector interface.
type MockCollector struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorMockRecorder
	isgomock struct{}
}

// MockCollectorMockRecorder is the mock recorder for MockCollector.
type MockCollectorMockRecorder struct {
	mock *MockCollector
}

// NewMockCollector creates a new mock instance.
func NewMockCollector(ctrl *gomock.Controller) *MockCollector {
	mock := &MockCollector{ctrl: ctrl}
	mock.recorder = &MockCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollector) EXPECT() *MockCollectorMockRecorder {
	return m.recorder
}

// AllAliveStorages mocks base method.
func (m *MockCollector) AllAliveStorages(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllAliveStorages", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllAliveStorages indicates an expected call of AllAliveStorages.
func (mr *MockCollectorMockRecorder) AllAliveStorages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllAliveStorages", reflect.TypeOf((*MockCollector)(nil).AllAliveStorages), ctx)
}

// Close mocks base method.
func (m *MockCollector) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCollectorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCollector)(nil).Close))
}

// FirstAliveStorage mocks base method.
func (m *MockCollector) FirstAliveStorage(ctx context.Context) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstAliveStorage", ctx)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstAliveStorage indicates an expected call of FirstAliveStorage.
func (mr *MockCollectorMockRecorder) FirstAliveStorage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstAliveStorage", reflect.TypeOf((*MockCollector)(nil).FirstAliveStorage), ctx)
}

// ReportOperationResult mocks base method.
func (m *MockCollector) ReportOperationResult(storage string, op OperationWeight, success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportOperationResult", storage, op, success)
}

// ReportOperationResult indicates an expected call of ReportOperationResult.
func (mr *MockCollectorMockRecorder) ReportOperationResult(storage, op, success any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportOperationResult", reflect.TypeOf((*MockCollector)(nil).ReportOperationResult), storage, op, success)
}

// SpecificStorage mocks base method.
func (m *MockCollector) SpecificStorage(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpecificStorage", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpecificStorage indicates an expected call of SpecificStorage.
func (mr *MockCollectorMockRecorder) SpecificStorage(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpecificStorage", reflect.TypeOf((*MockCollector)(nil).SpecificStorage), ctx, name)
}
