// Code generated by Yandex patched mockery v1.1.0. DO NOT EDIT.

package stagesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/wal-g/wal-g/internal/databases/mongo/models"

	sync "sync"
)

// Applier is an autogenerated mock type for the Applier type
type Applier struct {
	mock.Mock
}

// Apply provides a mock function with given fields: _a0, _a1, _a2
func (_m *Applier) Apply(_a0 context.Context, _a1 chan *models.Oplog, _a2 *sync.WaitGroup) (chan error, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 1 {
		rf, ok := ret.Get(0).(func(context.Context, chan *models.Oplog, *sync.WaitGroup) (chan error, error))
		if ok {
			return rf(_a0, _a1, _a2)
		}
	}

	var r0 chan error
	if rf, ok := ret.Get(0).(func(context.Context, chan *models.Oplog, *sync.WaitGroup) chan error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan error)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, chan *models.Oplog, *sync.WaitGroup) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
