// Code generated by Yandex patched mockery v1.1.0. DO NOT EDIT.

package stagesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/wal-g/wal-g/internal/databases/mongo/models"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: _a0
func (_m *Fetcher) Fetch(_a0 context.Context) (chan *models.Oplog, chan error, error) {
	ret := _m.Called(_a0)

	if len(ret) == 1 {
		rf, ok := ret.Get(0).(func(context.Context) (chan *models.Oplog, chan error, error))
		if ok {
			return rf(_a0)
		}
	}

	var r0 chan *models.Oplog
	if rf, ok := ret.Get(0).(func(context.Context) chan *models.Oplog); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *models.Oplog)
		}
	}

	var r1 chan error
	if rf, ok := ret.Get(1).(func(context.Context) chan error); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
