// Code generated by Yandex patched mockery v1.1.0. DO NOT EDIT.

package stagesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/wal-g/wal-g/internal/databases/mongo/models"
)

// GapHandler is an autogenerated mock type for the GapHandler type
type GapHandler struct {
	mock.Mock
}

// HandleGap provides a mock function with given fields: ctx, from, until, err
func (_m *GapHandler) HandleGap(ctx context.Context, from models.Timestamp, until models.Timestamp, err error) error {
	ret := _m.Called(ctx, from, until, err)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Timestamp, models.Timestamp, error) error); ok {
		r0 = rf(ctx, from, until, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
