// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wal-g/wal-g/pkg/storages/storage (interfaces: FolderExt)
//
// Generated by this command:
//
//	mockgen -destination=../../../test/mocks/mock_folder_ext.go -package mocks -build_flags -mod=readonly github.com/wal-g/wal-g/pkg/storages/storage FolderExt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	storage "github.com/wal-g/wal-g/pkg/storages/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockFolderExt is a mock of FolderExt interface.
type MockFolderExt struct {
	ctrl     *gomock.Controller
	recorder *MockFolderExtMockRecorder
	isgomock struct{}
}

// MockFolderExtMockRecorder is the mock recorder for MockFolderExt.
type MockFolderExtMockRecorder struct {
	mock *MockFolderExt
}

// NewMockFolderExt creates a new mock instance.
func NewMockFolderExt(ctrl *gomock.Controller) *MockFolderExt {
	mock := &MockFolderExt{ctrl: ctrl}
	mock.recorder = &MockFolderExtMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFolderExt) EXPECT() *MockFolderExtMockRecorder {
	return m.recorder
}

// CopyObject mocks base method.
func (m *MockFolderExt) CopyObject(ctx context.Context, srcPath, dstPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyObject", ctx, srcPath, dstPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockFolderExtMockRecorder) CopyObject(ctx, srcPath, dstPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyObject", reflect.TypeOf((*MockFolderExt)(nil).CopyObject), ctx, srcPath, dstPath)
}

// DeleteObjects mocks base method.
func (m *MockFolderExt) DeleteObjects(ctx context.Context, objects []storage.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjects", ctx, objects)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockFolderExtMockRecorder) DeleteObjects(ctx, objects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockFolderExt)(nil).DeleteObjects), ctx, objects)
}

// Exists mocks base method.
func (m *MockFolderExt) Exists(ctx context.Context, objectRelativePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, objectRelativePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockFolderExtMockRecorder) Exists(ctx, objectRelativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFolderExt)(nil).Exists), ctx, objectRelativePath)
}

// GetPath mocks base method.
func (m *MockFolderExt) GetPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPath indicates an expected call of GetPath.
func (mr *MockFolderExtMockRecorder) GetPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPath", reflect.TypeOf((*MockFolderExt)(nil).GetPath))
}

// GetSubFolder mocks base method.
func (m *MockFolderExt) GetSubFolder(subFolderRelativePath string) storage.Folder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubFolder", subFolderRelativePath)
	ret0, _ := ret[0].(storage.Folder)
	return ret0
}

// GetSubFolder indicates an expected call of GetSubFolder.
func (mr *MockFolderExtMockRecorder) GetSubFolder(subFolderRelativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubFolder", reflect.TypeOf((*MockFolderExt)(nil).GetSubFolder), subFolderRelativePath)
}

// GetVersioningEnabled mocks base method.
func (m *MockFolderExt) GetVersioningEnabled(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersioningEnabled", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetVersioningEnabled indicates an expected call of GetVersioningEnabled.
func (mr *MockFolderExtMockRecorder) GetVersioningEnabled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersioningEnabled", reflect.TypeOf((*MockFolderExt)(nil).GetVersioningEnabled), ctx)
}

// ListFolder mocks base method.
func (m *MockFolderExt) ListFolder(ctx context.Context) ([]storage.Object, []storage.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolder", ctx)
	ret0, _ := ret[0].([]storage.Object)
	ret1, _ := ret[1].([]storage.Folder)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFolder indicates an expected call of ListFolder.
func (mr *MockFolderExtMockRecorder) ListFolder(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolder", reflect.TypeOf((*MockFolderExt)(nil).ListFolder), ctx)
}

// ListFolderSegment mocks base method.
func (m *MockFolderExt) ListFolderSegment(ctx context.Context, startAfter, endBefore *string) ([]storage.Object, []storage.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolderSegment", ctx, startAfter, endBefore)
	ret0, _ := ret[0].([]storage.Object)
	ret1, _ := ret[1].([]storage.Folder)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFolderSegment indicates an expected call of ListFolderSegment.
func (mr *MockFolderExtMockRecorder) ListFolderSegment(ctx, startAfter, endBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolderSegment", reflect.TypeOf((*MockFolderExt)(nil).ListFolderSegment), ctx, startAfter, endBefore)
}

// PutObject mocks base method.
func (m *MockFolderExt) PutObject(ctx context.Context, name string, content io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, name, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockFolderExtMockRecorder) PutObject(ctx, name, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockFolderExt)(nil).PutObject), ctx, name, content)
}

// ReadObject mocks base method.
func (m *MockFolderExt) ReadObject(ctx context.Context, objectRelativePath string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadObject", ctx, objectRelativePath)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadObject indicates an expected call of ReadObject.
func (mr *MockFolderExtMockRecorder) ReadObject(ctx, objectRelativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadObject", reflect.TypeOf((*MockFolderExt)(nil).ReadObject), ctx, objectRelativePath)
}

// SetVersioningEnabled mocks base method.
func (m *MockFolderExt) SetVersioningEnabled(ctx context.Context, enable bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVersioningEnabled", ctx, enable)
}

// SetVersioningEnabled indicates an expected call of SetVersioningEnabled.
func (mr *MockFolderExtMockRecorder) SetVersioningEnabled(ctx, enable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVersioningEnabled", reflect.TypeOf((*MockFolderExt)(nil).SetVersioningEnabled), ctx, enable)
}

// Validate mocks base method.
func (m *MockFolderExt) Validate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockFolderExtMockRecorder) Validate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockFolderExt)(nil).Validate), ctx)
}
