// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wal-g/wal-g/pkg/storages/storage (interfaces: FolderExt)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	storage "github.com/wal-g/wal-g/pkg/storages/storage"
)

// MockFolderExt is a mock of FolderExt interface.
type MockFolderExt struct {
	ctrl     *gomock.Controller
	recorder *MockFolderExtMockRecorder
}

// MockFolderExtMockRecorder is the mock recorder for MockFolderExt.
type MockFolderExtMockRecorder struct {
	mock *MockFolderExt
}

// NewMockFolderExt creates a new mock instance.
func NewMockFolderExt(ctrl *gomock.Controller) *MockFolderExt {
	mock := &MockFolderExt{ctrl: ctrl}
	mock.recorder = &MockFolderExtMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFolderExt) EXPECT() *MockFolderExtMockRecorder {
	return m.recorder
}

// CopyObject mocks base method.
func (m *MockFolderExt) CopyObject(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyObject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockFolderExtMockRecorder) CopyObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyObject", reflect.TypeOf((*MockFolderExt)(nil).CopyObject), arg0, arg1)
}

// DeleteObjects mocks base method.
func (m *MockFolderExt) DeleteObjects(arg0 []storage.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjects", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockFolderExtMockRecorder) DeleteObjects(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockFolderExt)(nil).DeleteObjects), arg0)
}

// Exists mocks base method.
func (m *MockFolderExt) Exists(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockFolderExtMockRecorder) Exists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFolderExt)(nil).Exists), arg0)
}

// GetPath mocks base method.
func (m *MockFolderExt) GetPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPath indicates an expected call of GetPath.
func (mr *MockFolderExtMockRecorder) GetPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPath", reflect.TypeOf((*MockFolderExt)(nil).GetPath))
}

// GetSubFolder mocks base method.
func (m *MockFolderExt) GetSubFolder(arg0 string) storage.Folder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubFolder", arg0)
	ret0, _ := ret[0].(storage.Folder)
	return ret0
}

// GetSubFolder indicates an expected call of GetSubFolder.
func (mr *MockFolderExtMockRecorder) GetSubFolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubFolder", reflect.TypeOf((*MockFolderExt)(nil).GetSubFolder), arg0)
}

// GetVersioningEnabled mocks base method.
func (m *MockFolderExt) GetVersioningEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersioningEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetVersioningEnabled indicates an expected call of GetVersioningEnabled.
func (mr *MockFolderExtMockRecorder) GetVersioningEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersioningEnabled", reflect.TypeOf((*MockFolderExt)(nil).GetVersioningEnabled))
}

// ListFolder mocks base method.
func (m *MockFolderExt) ListFolder() ([]storage.Object, []storage.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolder")
	ret0, _ := ret[0].([]storage.Object)
	ret1, _ := ret[1].([]storage.Folder)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFolder indicates an expected call of ListFolder.
func (mr *MockFolderExtMockRecorder) ListFolder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolder", reflect.TypeOf((*MockFolderExt)(nil).ListFolder))
}

// ListFolderSegment mocks base method.
func (m *MockFolderExt) ListFolderSegment(arg0, arg1 *string) ([]storage.Object, []storage.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolderSegment", arg0, arg1)
	ret0, _ := ret[0].([]storage.Object)
	ret1, _ := ret[1].([]storage.Folder)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFolderSegment indicates an expected call of ListFolderSegment.
func (mr *MockFolderExtMockRecorder) ListFolderSegment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolderSegment", reflect.TypeOf((*MockFolderExt)(nil).ListFolderSegment), arg0, arg1)
}

// PutObject mocks base method.
func (m *MockFolderExt) PutObject(arg0 string, arg1 io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockFolderExtMockRecorder) PutObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockFolderExt)(nil).PutObject), arg0, arg1)
}

// PutObjectWithContext mocks base method.
func (m *MockFolderExt) PutObjectWithContext(arg0 context.Context, arg1 string, arg2 io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObjectWithContext", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObjectWithContext indicates an expected call of PutObjectWithContext.
func (mr *MockFolderExtMockRecorder) PutObjectWithContext(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObjectWithContext", reflect.TypeOf((*MockFolderExt)(nil).PutObjectWithContext), arg0, arg1, arg2)
}

// ReadObject mocks base method.
func (m *MockFolderExt) ReadObject(arg0 string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadObject", arg0)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadObject indicates an expected call of ReadObject.
func (mr *MockFolderExtMockRecorder) ReadObject(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadObject", reflect.TypeOf((*MockFolderExt)(nil).ReadObject), arg0)
}

// SetVersioningEnabled mocks base method.
func (m *MockFolderExt) SetVersioningEnabled(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVersioningEnabled", arg0)
}

// SetVersioningEnabled indicates an expected call of SetVersioningEnabled.
func (mr *MockFolderExtMockRecorder) SetVersioningEnabled(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVersioningEnabled", reflect.TypeOf((*MockFolderExt)(nil).SetVersioningEnabled), arg0)
}

// Validate mocks base method.
func (m *MockFolderExt) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockFolderExtMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockFolderExt)(nil).Validate))
}
