// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wal-g/wal-g/pkg/storages/storage (interfaces: Folder)
//
// Generated by this command:
//
//	mockgen -destination=../../../test/mocks/mock_folder.go -package mocks -build_flags -mod=readonly github.com/wal-g/wal-g/pkg/storages/storage Folder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	storage "github.com/wal-g/wal-g/pkg/storages/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockFolder is a mock of Folder interface.
type MockFolder struct {
	ctrl     *gomock.Controller
	recorder *MockFolderMockRecorder
	isgomock struct{}
}

// MockFolderMockRecorder is the mock recorder for MockFolder.
type MockFolderMockRecorder struct {
	mock *MockFolder
}

// NewMockFolder creates a new mock instance.
func NewMockFolder(ctrl *gomock.Controller) *MockFolder {
	mock := &MockFolder{ctrl: ctrl}
	mock.recorder = &MockFolderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFolder) EXPECT() *MockFolderMockRecorder {
	return m.recorder
}

// CopyObject mocks base method.
func (m *MockFolder) CopyObject(ctx context.Context, srcPath, dstPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyObject", ctx, srcPath, dstPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockFolderMockRecorder) CopyObject(ctx, srcPath, dstPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyObject", reflect.TypeOf((*MockFolder)(nil).CopyObject), ctx, srcPath, dstPath)
}

// DeleteObjects mocks base method.
func (m *MockFolder) DeleteObjects(ctx context.Context, objects []storage.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjects", ctx, objects)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockFolderMockRecorder) DeleteObjects(ctx, objects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockFolder)(nil).DeleteObjects), ctx, objects)
}

// Exists mocks base method.
func (m *MockFolder) Exists(ctx context.Context, objectRelativePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, objectRelativePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockFolderMockRecorder) Exists(ctx, objectRelativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFolder)(nil).Exists), ctx, objectRelativePath)
}

// GetPath mocks base method.
func (m *MockFolder) GetPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPath indicates an expected call of GetPath.
func (mr *MockFolderMockRecorder) GetPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPath", reflect.TypeOf((*MockFolder)(nil).GetPath))
}

// GetSubFolder mocks base method.
func (m *MockFolder) GetSubFolder(subFolderRelativePath string) storage.Folder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubFolder", subFolderRelativePath)
	ret0, _ := ret[0].(storage.Folder)
	return ret0
}

// GetSubFolder indicates an expected call of GetSubFolder.
func (mr *MockFolderMockRecorder) GetSubFolder(subFolderRelativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubFolder", reflect.TypeOf((*MockFolder)(nil).GetSubFolder), subFolderRelativePath)
}

// GetVersioningEnabled mocks base method.
func (m *MockFolder) GetVersioningEnabled(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersioningEnabled", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetVersioningEnabled indicates an expected call of GetVersioningEnabled.
func (mr *MockFolderMockRecorder) GetVersioningEnabled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersioningEnabled", reflect.TypeOf((*MockFolder)(nil).GetVersioningEnabled), ctx)
}

// ListFolder mocks base method.
func (m *MockFolder) ListFolder(ctx context.Context) ([]storage.Object, []storage.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolder", ctx)
	ret0, _ := ret[0].([]storage.Object)
	ret1, _ := ret[1].([]storage.Folder)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFolder indicates an expected call of ListFolder.
func (mr *MockFolderMockRecorder) ListFolder(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolder", reflect.TypeOf((*MockFolder)(nil).ListFolder), ctx)
}

// PutObject mocks base method.
func (m *MockFolder) PutObject(ctx context.Context, name string, content io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, name, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockFolderMockRecorder) PutObject(ctx, name, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockFolder)(nil).PutObject), ctx, name, content)
}

// ReadObject mocks base method.
func (m *MockFolder) ReadObject(ctx context.Context, objectRelativePath string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadObject", ctx, objectRelativePath)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadObject indicates an expected call of ReadObject.
func (mr *MockFolderMockRecorder) ReadObject(ctx, objectRelativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadObject", reflect.TypeOf((*MockFolder)(nil).ReadObject), ctx, objectRelativePath)
}

// SetVersioningEnabled mocks base method.
func (m *MockFolder) SetVersioningEnabled(ctx context.Context, enable bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVersioningEnabled", ctx, enable)
}

// SetVersioningEnabled indicates an expected call of SetVersioningEnabled.
func (mr *MockFolderMockRecorder) SetVersioningEnabled(ctx, enable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVersioningEnabled", reflect.TypeOf((*MockFolder)(nil).SetVersioningEnabled), ctx, enable)
}

// Validate mocks base method.
func (m *MockFolder) Validate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockFolderMockRecorder) Validate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockFolder)(nil).Validate), ctx)
}
