// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/wal-g/wal-g/pkg/storages/storage"
)

// Folder is an autogenerated mock type for the Folder type
type Folder struct {
	mock.Mock
}

// CopyObject provides a mock function with given fields: ctx, srcPath, dstPath
func (_m *Folder) CopyObject(ctx context.Context, srcPath string, dstPath string) error {
	ret := _m.Called(ctx, srcPath, dstPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, srcPath, dstPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteObjects provides a mock function with given fields: ctx, objects
func (_m *Folder) DeleteObjects(ctx context.Context, objects []storage.Object) error {
	ret := _m.Called(ctx, objects)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []storage.Object) error); ok {
		r0 = rf(ctx, objects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, objectRelativePath
func (_m *Folder) Exists(ctx context.Context, objectRelativePath string) (bool, error) {
	ret := _m.Called(ctx, objectRelativePath)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, objectRelativePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, objectRelativePath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectRelativePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPath provides a mock function with given fields:
func (_m *Folder) GetPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSubFolder provides a mock function with given fields: subFolderRelativePath
func (_m *Folder) GetSubFolder(subFolderRelativePath string) storage.Folder {
	ret := _m.Called(subFolderRelativePath)

	var r0 storage.Folder
	if rf, ok := ret.Get(0).(func(string) storage.Folder); ok {
		r0 = rf(subFolderRelativePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.Folder)
		}
	}

	return r0
}

// ListFolder provides a mock function with given fields: ctx
func (_m *Folder) ListFolder(ctx context.Context) ([]storage.Object, []storage.Folder, error) {
	ret := _m.Called(ctx)

	var r0 []storage.Object
	var r1 []storage.Folder
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]storage.Object, []storage.Folder, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []storage.Object); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []storage.Folder); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]storage.Folder)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PutObject provides a mock function with given fields: ctx, name, content
func (_m *Folder) PutObject(ctx context.Context, name string, content io.Reader) error {
	ret := _m.Called(ctx, name, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, name, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadObject provides a mock function with given fields: ctx, objectRelativePath
func (_m *Folder) ReadObject(ctx context.Context, objectRelativePath string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, objectRelativePath)

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, objectRelativePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, objectRelativePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectRelativePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFolder creates a new instance of Folder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFolder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Folder {
	mock := &Folder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
