FROM wal-g/golang:latest as build

WORKDIR /go/src/github.com/wal-g/wal-g

COPY go.mod go.mod
COPY vendor/ vendor/
COPY internal/ internal/
COPY pkg/ pkg/
COPY cmd/ cmd/
COPY main/ main/
COPY utility/ utility/

# we test wal-g logic, not our deps. So, no brotli in these tests.
RUN cd main/mysql && \
    go build -mod vendor -race -o wal-g -ldflags "-s -w"

FROM wal-g/mysql8:latest

COPY --from=build /go/src/github.com/wal-g/wal-g/main/mysql/wal-g /usr/bin

RUN mkdir /root/testtools

COPY docker/mysql_tests/scripts/ /tmp

CMD /tmp/run_integration_tests.sh  -p /tmp/mysql8_tests
