FROM wal-g/golang:latest AS build
WORKDIR /go/src/github.com/wal-g/wal-g

COPY go.mod go.mod
COPY go.sum go.sum
COPY vendor/ vendor/
COPY internal/ internal/
COPY pkg/ pkg/
COPY cmd/ cmd/
COPY main/ main/
COPY utility/ utility/
COPY Makefile Makefile

# We test WAL-G logic, not optional compression dependencies. Race detection is
# enabled on x86_64 consistently with the existing MySQL 8 image.
RUN make $( [ "$(uname -m)" = "x86_64" ] && echo ENABLE_RACE_DETECTION=1 ) mysql_build

FROM wal-g/mysql97:latest

COPY --from=build /go/src/github.com/wal-g/wal-g/main/mysql/wal-g /usr/bin/wal-g

COPY docker/mysql_tests/scripts/ /tmp

CMD ["/tmp/run_integration_tests.sh", "-p", "/tmp/mysql97_tests"]
