FROM wal-g/golang:latest AS build
ENV GOEXPERIMENT=jsonv2
WORKDIR /go/src/github.com/wal-g/wal-g

COPY go.mod go.mod
COPY vendor/ vendor/
COPY internal/ internal/
COPY pkg/ pkg/
COPY cmd/ cmd/
COPY main/ main/
COPY utility/ utility/

# we test wal-g logic, not our deps. So, no brotli in these tests.
# Note: `-race` fails on ARM64 when ubuntu:bionic used: race runtime needs outline-atomics
# helpers from libgcc 10+, which the bionic-based wal-g/golang base doesn't have.
RUN cd main/mysql && \
    if [ "$(uname -m)" = "x86_64" ]; then RACE="-race"; else RACE=""; fi && \
    go build -mod vendor $RACE -o wal-g -ldflags "-s -w"

FROM wal-g/mysql8:latest

COPY --from=build /go/src/github.com/wal-g/wal-g/main/mysql/wal-g /usr/bin

RUN mkdir /root/testtools

COPY docker/mysql_tests/scripts/ /tmp

CMD /tmp/run_integration_tests.sh  -p /tmp/mysql8_tests
