name: Run vulnerability check
on:
  push:
  pull_request:

permissions:
  contents: read
  
env:
  GO_VERSION: "1.25"
  USE_BROTLI: 1
  USE_LIBSODIUM: 1
  USE_LZO: 1
  GOEXPERIMENT: jsonv2

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends --no-install-suggests liblzo2-dev brotli libsodium-dev

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - id: govulncheck
        uses: golang/govulncheck-action@v1

      - name: Run Trivy scanner
        if: always()
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          cache: 'false'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_SCANNERS: vuln