name: windows native build

on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.25"

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: windows build smoke test
    runs-on: windows-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v7

      - name: Set up Go 1.x
        uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
        id: go

      - name: Load libsodium version
        run: |
          $version = (Get-Content .github/versions/libsodium-version -Raw).Trim()
          "LIBSODIUM_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build dependencies
        run: |
          curl --retry 5 --retry-delay 0 -sL "https://github.com/jedisct1/libsodium/releases/download/$env:LIBSODIUM_VERSION-RELEASE/libsodium-$env:LIBSODIUM_VERSION-mingw.tar.gz" -o "libsodium-$env:LIBSODIUM_VERSION-mingw.tar.gz"
          tar -xf .\libsodium-$env:LIBSODIUM_VERSION-mingw.tar.gz
          mkdir tmp
          mv libsodium-win64 ./tmp/libsodium
          make deps
          <#
          Some tests create hardlinks and Windows cannot create hardlinks across volumes.
          So, set TMP to RUNNER_TEMP; ideally avoiding volume crossing like:
          https://github.com/actions/runner-images/issues/12386
          https://github.com/actions/runner-images/issues/12416
          https://github.com/actions/runner-images/issues/12744
          #>
          echo "TMP=$env:RUNNER_TEMP" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Run unittests
        run: |
          make unittest

      - name: Build wal-g for SQL Server and PostgreSQL
        run: |
          make sqlserver_build pg_build
